name: sync_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.6.0

  # Drift (SQLite) stack
  drift: ^2.18.0
  drift_flutter: ^0.2.0             # convenience extras for Flutter
  sqlite3_flutter_libs: ^0.5.24      # <-- REQUIRED for Windows/macOS/Linux (bundles native sqlite3)
  path: ^1.9.0
  path_provider: ^2.1.4

  # Optional (you can keep or remove if unused)
  sqflite: ^2.3.3                    # not used by Drift/NativeDatabase, but harmless if you also use sqflite elsewhere
  connectivity_plus: ^6.0.5
  uuid: ^4.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  drift_dev: ^2.18.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
